### PR TITLE
Update copyright dates

### PR DESCRIPTION
**Pull request by nburka**

### CODE REVIEW

**Comment by isaacgrant** [comment]
Following files have broken copyright block and should be updated:
 * `Store/StoreCategoryPathEntry.php`
 * `Store/dataobjects/StoreQuantityDiscountRegionBinding.php`
 * `Store/dataobjects/StoreItemRegionBinding.php`

**Comment by nburka** [comment]
> Following files have broken copyright block and should be updated

Fixed in 98949f3

**Comment by isaacgrant** [comment]
`sql/tables/AccountAddress.sql` has changes that are outside the scope of this PR.

**Comment by isaacgrant** [comment]
R+ beyond the sql change being removed.

**Pull request merged**
