### PR TITLE
Remove obsolete browser hacks

### PR DESCRIPTION
**Pull request by sgarrity**
Depends on:
https://github.com/silverorange/swat/pull/58
https://github.com/silverorange/admin/pull/48
https://github.com/silverorange/site/pull/162
https://github.com/silverorange/academy/pull/182
https://github.com/silverorange/Cme/pull/68

### CODE REVIEW

**Comment by sgarrity** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;ZesPlEw7&#x2F;529-clean-up-obsolete-css-vendor-prefixes-in-packges"> Clean up obsolete css vendor prefixes in packges</a>

**Comment by nburka** [comment]
Hi there Steven. I hope you get this notification.

**Comment by nburka** [comment]
Another notification should come your way.

**Comment by sgarrity** [comment]
Thanks for testing my notifications. I'm now testing yours!

**Comment by sgarrity** [comment]
Another test!

**Pull request merged**
